### ISSUE TITLE
AbortController is not defined --- Powerplant Types fail to load

### ISSUE THREAD

**Issue by kdmonroe** [odoe/jsapi-nextjs#1]
The initial powerplant types fails to load locally in development, and also once [deployed in Vercel](https://jsapi-nextjs.vercel.app)

Local compiler error reads - 

> error - (api)\node_modules\@arcgis\core\request.js (5:1615) @ C
> ReferenceError: AbortController is not defined

**Comment by odoe** [comment]
Interesting. I know the why, it need the polyfill for node like here
https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-node/native-esm/request.mjs#L5

What's weird is that I never hit this issue, but I used Heroku. No problem, I'll get an update to this soon, thanks!

**Comment by odoe** [comment]
Added the polyfill [here](https://github.com/odoe/jsapi-nextjs/commit/77ce7e520225fc55e76b15615290d1395d5ea94a), can you see if that fixes it for you? Thanks.

**Comment by kdmonroe** [comment]
Yup, it's working now! Thanks
